//Criar uma variável idade e mostrar:
//"Eu tenho_____ anos de idade"
let idade = 39;
//console.log("Eu tenho" + idade + "anos de idade");

//Criar duas variáveis "cidade" e "estado" e exiba:
//Eu moro em _____ - _____.
let cidade = "Maringá";
let estado = "Paraná";
console.log("Eu moro em ${cidade} - ${estado}");

//Criar duas variáveis e mostre:
//a soma, a subtração, a multiplicação, a divisão, o dobro, o triplo, a metade e o quadrado 
let n1 = 10;
let n2 = 5;
let soma = n1 + n2;
console.log (`A soma de ${n1} e ${n2} é ${soma}`);
let subt = n1 - n2;
console.log (`A subtração de ${n1} e ${n2} é ${subt}`);
let mult =n1 * n2;
console.log (`A multiplicação de ${n1} e ${n2} é ${mult}`);
let divisao = n1/n2;
console.log (`A divisão de ${n1} e ${n1} é ${divisao}`);
let dobro = n1 * 2;
console.log (`O dobro de ${n1} e ${n1} é ${dobro}`);
let triplo = n2 * 3;
console.log (`O triplo de ${n1} e ${n2} é ${triplo}`);
let metade = n1 / 2
console.log (`A metade de ${n1} e ${n1} é ${metade}`);
let quadrado = n1 ** 2;
console.log (`O quadrado de ${n1} e ${n2} é ${quadrado}`);
